# **Assignment For Numpy**

In [7]:
import numpy as np

2. Create a null vector of size 10 

In [4]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [6]:
w = np.arange(10,19)
print(w)

[10 11 12 13 14 15 16 17 18]


4. Find the shape of previous array in question 3

In [9]:
x.shape

(10,)

5. Print the type of the previous array in question 3

In [13]:
print(x.dtype)

float64


In [ ]:

# 6. Print the numpy version and the configuration


In [14]:
print(np.__version__)
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SAPHIE KHAN/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/SAPHIE KHAN/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/SAPHIE KHAN/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.

7. Print the dimension of the array in question 3


In [18]:
b = np.zeros(10)

print("dimension = ",b.ndim)
print("shape = ",b.shape)

dimension =  1
shape =  (10,)


8. Create a boolean array with all the True values

In [25]:
b = np.full((1,10),2)
z_bool = b<3
print(z_bool)

[[ True  True  True  True  True  True  True  True  True  True]]


9. Create a two dimensional array




In [7]:
arr = np.full((2,3),2)
arr

array([[2, 2, 2],
       [2, 2, 2]])

10. Create a three dimensional array



In [9]:
arr = np.full((2,2,2),2)
arr

array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]])

11. Reverse a vector (first element becomes last)

In [12]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr2 = arr[::-1]
arr2

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [14]:
arr = np.zeros(10)
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [15]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
arr = np.array([1,2,3,4,5])
print(arr.dtype)
arr=arr.astype("float64")
print(arr.dtype)

int32
float64


In [23]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0,4,1],[7,2,12]])

arr1*arr2


array([[ 0,  8,  3],
       [28, 10, 72]])



##### 16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

16 - Make an array by comparing both the arrays provided above

In [13]:
a = np.array([1,2,3])
b=np.array([0,7,3])

c = a!=b
c

array([ True,  True, False])

17. Extract all odd numbers from arr with values(0-9)

In [27]:
g = np.arange(10)
result = []
for i in g:
    if i % 2 != 0:
        result.append(g[i])
w=np.array(result)
print(g)
print(w)

[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [26]:
g = np.arange(10)
result = []
for i in g:
    if i % 2 != 0:
        g[i]=-1
        
print(g)

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [28]:
arr = np.arange(10)
arr[[5,6,7,8]]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [34]:
a = np.ones((5,5))
print(a)
b= np.zeros((3,3))
print(b)

a[1:4,1:4]=b
a

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [35]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d[1,1]=12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [36]:
arr3d = np.array([[[1, 2, 3],
                   [4, 5, 6]],
                  
                  [[7, 8, 9],
                   [10, 11, 12]]])
arr3d[0,0,:]=64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [40]:
a = np.array([[0,1],[4,5],[6,7],[8,9]])
b = a[0]
b

array([0, 1])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [41]:
a = np.array([[0,1],[4,5],[6,7],[8,9]])
b = a[1]
b

array([4, 5])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [42]:
a = np.array([[0,1,2],
              [4,5,3],
              [6,7,4],
              [8,9,5]])
b = a[0:2,2]
b

array([2, 3])

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [46]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
c=np.intersect1d(a,b)
c

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [52]:
z=np.where(np.in1d(a, b))
z

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [58]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(names)
print(data)

data[names!='Will']

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 1.54832475 -0.2957227  -1.46412182 -1.04868617]
 [ 1.10190824 -1.28933451  0.58186623 -0.37217678]
 [-0.63587141  0.16520335 -0.50328444  0.54391911]
 [ 0.6385704  -0.00860036  0.14006329  0.07623264]
 [-0.75779204 -1.15143763  1.69748616  1.53918809]
 [-2.17793185  0.06449205 -0.24339762 -0.72514508]
 [-1.45744902 -0.49616104  1.94666489  0.67240222]]


array([[ 1.54832475, -0.2957227 , -1.46412182, -1.04868617],
       [ 1.10190824, -1.28933451,  0.58186623, -0.37217678],
       [ 0.6385704 , -0.00860036,  0.14006329,  0.07623264],
       [-2.17793185,  0.06449205, -0.24339762, -0.72514508],
       [-1.45744902, -0.49616104,  1.94666489,  0.67240222]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [61]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
print(names)
print(data)

data[(names!='Will')&(names!='Joe')]

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 1.33237167  0.32711678 -0.93534564  0.15747946]
 [-0.23991754  0.29123742 -1.30608835  1.3538005 ]
 [-1.01603408 -0.37010067 -0.72920284  1.80766359]
 [-0.21978529 -1.24826069  1.79666677  0.60597502]
 [ 0.76733276  1.01839736  0.92617935 -0.54540333]
 [ 0.25170319 -0.21366914 -0.99201086  0.44588125]
 [ 0.44052645 -0.24092616  1.5627184   0.36435281]]


array([[ 1.33237167,  0.32711678, -0.93534564,  0.15747946],
       [-0.21978529, -1.24826069,  1.79666677,  0.60597502]])

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [64]:
np.random.randint(1,15,size=(5,3))

array([[ 4, 11, 14],
       [ 1,  1,  1],
       [ 3,  9,  9],
       [14, 12,  9],
       [13,  4,  7]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [10]:
z=np.random.uniform(1, 16, size=(2,2,4))


33. Swap axes of the array you created in Question 32

In [11]:
np.swapaxes(z,0,2)

array([[[ 7.28262432, 14.32263411],
        [12.08096822,  1.76979033]],

       [[11.59548646,  6.03378025],
        [13.42715764,  5.13568377]],

       [[ 1.47949295,  4.64899636],
        [ 3.04928146, 11.87003088]],

       [[11.37681167,  6.69280402],
        [14.98488916,  1.59131866]]])

In [14]:
z=np.arange(10)
z=np.sqrt(z)
z[z<0.5]=0
z

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [18]:
a = np.random.rand(12)
b = np.random.rand(12)
c = np.maximum(a,b)
c

array([0.98650143, 0.55251964, 0.65446414, 0.67890851, 0.80701841,
       0.51534036, 0.88876779, 0.0661514 , 0.81919918, 0.83377775,
       0.57620161, 0.96141659])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [25]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
z=np.sort(np.unique(names))
print(z)

['Bob' 'Joe' 'Will']


37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [28]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(a, b) 

array([1, 2, 3, 4])

In [3]:

print("Printing Original array")
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = np.array([[10,10,10]])
print("Array after inserting column 2 on axis 1")
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [5]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [10]:
a = np.array([1,2,3])
print(a)
print("element size : ",a.itemsize)
print("total size : ",a.nbytes)
print("total elements : ",a.size)

[1 2 3]
element size :  4
total size :  12
total elements :  3


In [22]:
#Array slicing
z = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14,]])
print(z[1,3])
print(z[1,:])
print(z[:,3])
print(z[1,1:-1:2])

11
[ 8  9 10 11 12 13 14]
[ 4 11]
[ 9 11 13]


In [23]:
z[::]=2
z

array([[2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 2]])

In [25]:
#three dimensional array and then get specific element
threeD = np.array([[[1,2,3],[4,5,6]],[[5,6,7],[8,9,10]]])
print(threeD)
print(threeD[0,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 5  6  7]
  [ 8  9 10]]]
6


In [26]:
threeD[:,0,:]=2
threeD

array([[[ 2,  2,  2],
        [ 4,  5,  6]],

       [[ 2,  2,  2],
        [ 8,  9, 10]]])

In [27]:
#create an array like already present
np.full_like(threeD,4)


array([[[4, 4, 4],
        [4, 4, 4]],

       [[4, 4, 4],
        [4, 4, 4]]])

In [28]:
#random number generation
np.random.rand(4,2)

array([[0.45175743, 0.40415574],
       [0.57824576, 0.73150054],
       [0.0320026 , 0.33208757],
       [0.93288707, 0.65955006]])

In [35]:
#Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
r1

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [41]:
#create a specific shape
b = np.ones((5,5))
print(b)
z = np.zeros((3,3))
z[1,1]=32
b[1:4,1:4]=z
b

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


array([[ 1.,  1.,  1.,  1.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  0., 32.,  0.,  1.],
       [ 1.,  0.,  0.,  0.,  1.],
       [ 1.,  1.,  1.,  1.,  1.]])

In [43]:
#array multiplied by scalar
a = np.array([1,2,3,4,5,6])
print(a)
a*2

[1 2 3 4 5 6]


array([ 2,  4,  6,  8, 10, 12])

####Linear Algebra

In [46]:
#matrix product
a = np.ones((2,3))
print(a)
b = np.full((3,2),5)
print(b)
x=np.matmul(a,b)
print(x)

[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]
[[15. 15.]
 [15. 15.]]


In [47]:
#find the determinant
np.linalg.det(x)

0.0

In [48]:
#sum of all elements in array
np.sum(x)

60.0

In [56]:
#find max value in each column
arr = np.array([[1,23,3,4],[6,7,8,9]])
print(np.max(arr,axis=0))

[ 6 23  8  9]


In [58]:
#reshape
arr = np.array([[1,2,3,4],[45,6,7,8]])
print(arr.shape)
after = arr.reshape(4,2)
print(after.shape)

(2, 4)
(4, 2)


In [2]:
#stacking
a = np.array([1,2,3])
b = np.array([4,5,6])

In [7]:
print("horizontal stack ",np.hstack([a,b]))
print("vertical stack",np.vstack((a,b)))

horizontal stack  [1 2 3 4 5 6]
vertical stack [[1 2 3]
 [4 5 6]]


In [8]:
#extract values greater than 2 from array
a = np.array([1,2,3,4,5,6,7,8])
b = a[a>2]
print(b)

[3 4 5 6 7 8]


In [9]:
#create a boolean array
z = np.full((3,3),True,dtype=bool)
z

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
z = np.arange(10)
z=z[z%2==1]
z

array([1, 3, 5, 7, 9])

In [13]:
z = np.arange(10)
z[z%2==1]=-1
z

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [15]:
w = np.arange(10)
z = np.where(w%2==1,7,w)
print(w)
print(z)

[0 1 2 3 4 5 6 7 8 9]
[0 7 2 7 4 7 6 7 8 7]


In [17]:
saffi = np.arange(10)
saffi.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [22]:
b = np.repeat(1,10).reshape(2,-1)
a = np.arange(10).reshape(2,-1)
np.concatenate([a, b], axis=0)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
b = np.repeat(1,10).reshape(2,-1)
a = np.arange(10).reshape(2,-1)
np.concatenate([a, b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [26]:
a = np.array([1,2,1,2,1,2])
b = np.array([3,2,3,2,3,2])
np.where(a==b)

(array([1, 3, 5], dtype=int64),)

In [27]:
a = np.arange(15)

index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [31]:
a = np.arange(9).reshape(3,3)
print(a)
a[:, [1,0,2]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [32]:
#reverse column
arr = np.arange(9).reshape(3,3)
print(arr)
arr[:, ::-1]

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [37]:
rand_arr = np.random.random([5,3])
print(rand_arr)
np.set_printoptions(precision=3)
rand_arr

[[0.248081   0.57909702 0.70381898]
 [0.6293417  0.46540883 0.28785238]
 [0.94045493 0.79443735 0.40414793]
 [0.21350245 0.40741387 0.34931025]
 [0.92178448 0.72662286 0.47647349]]


array([[0.248, 0.579, 0.704],
       [0.629, 0.465, 0.288],
       [0.94 , 0.794, 0.404],
       [0.214, 0.407, 0.349],
       [0.922, 0.727, 0.476]])

In [39]:
np.set_printoptions(threshold=6)
a = np.arange(15)
print(a)

[ 0  1  2 ... 12 13 14]


In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

Smax, Smin = sepallength.max(), sepallength.min()
S = (sepallength - Smin)/(Smax - Smin)

In [46]:
arr1 = np.arange(3)
arr2 = np.arange(3,7)
arr3 = np.arange(7,10)

array_of_arrays = np.array([arr1, arr2, arr3])
arr_2d = np.concatenate(array_of_arrays)
arr_2d

array([0, 1, 2, ..., 7, 8, 9])